# Server
server.port=${PORT:8080}

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6qit6ia214c739g3n20-a.oregon-postgres.render.com:5432/studentfeedbackdb
spring.datasource.username=rishi_karthikeyan
spring.datasource.password=f4bVER604TwtXRxzBiD98jl3dOKcgpAy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=feedbackSystemSecretKey2024SuperLongSecureKeyForJWTSigning1234567890
app.jwt.expiration=86400000

# Logging
logging.level.com.feedbacksystem=DEBUG
logging.level.org.springframework.security=DEBUG
